language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

script:
  - python setup.py build install

notifications:
  emails:
    - aiokada@hgc.jp
  on_success: change
  on_failure: always
