# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: UnitTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install -y npm nodejs
        python -m pip install --upgrade pip
        pip install coverage
        pip install .
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with unittest
      run: |
        coverage run --source=./scripts setup.py test
        coverage report
        bash tests/build_example.sh
        cd tests
        npm i -g npm
        npm install
        npm test
